#!/bin/sh
#

# parametros
# archivos
SIM=agro
MA=$SIM.ma
EV=$SIM.ev
LOG=$SIM.log
OUT=$SIM.out
#LOG_FULL=$LOG.full
# componente a graficar (CELLDEVS)
COM=campo

# ejecutables
SIMU_DIR=/opt/simu
#SIMU_DIR=$HOME/sed/cd++
SIMU=$SIMU_DIR/cd++
DRAWLOG=$SIMU_DIR/drawlog
#LOGBUFFER=$SIMU_DIR/logbuffer

# tiempos
TIME=00:00:20:000
STEP=00:00:00:001

#DEBUG="-p$SIM.parser -v$SIM.eval -r"

rm -f $LOG* $DRW $OUT

SIMU_ARGS="-m$MA"
[ -n "$TIME" ]  &&  SIMU_ARGS="$SIMU_ARGS -t$TIME"
[ -n "$EV" ]    &&  SIMU_ARGS="$SIMU_ARGS -e$EV"
[ -n "$LOG" ]   &&  SIMU_ARGS="$SIMU_ARGS -l$LOG"
[ -n "$OUT" ]   &&  SIMU_ARGS="$SIMU_ARGS -o$OUT"
[ -n "$DEBUG" ] &&  SIMU_ARGS="$SIMU_ARGS $DEBUG"


if [ -z "$DEBUGGER" ]; then
    time $SIMU $SIMU_ARGS
else
    $DEBUGGER $SIMU --pargs $SIMU_ARGS
fi

# drawlog
# tiempos
STEP=00:00:00:100

# grafica puertos

PORT=amb
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > $DRWVALUE

PORT=pro
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > $DRWVALUE

PORT=eme
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > $DRWVALUE

PORT=mgm
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > $DRWVALUE

PORT=lu1
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w4 -p0 -n$PORT > $DRWVALUE

PORT=lu2
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w4 -p0 -n$PORT > $DRWVALUE

PORT=lu3
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w4 -p0 -n$PORT > $DRWVALUE

PORT=ue_cota
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > $DRWVALUE

PORT=ua_cota
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > $DRWVALUE

PORT=ua_tipo
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > $DRWVALUE

PORT=deg
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > $DRWVALUE

PORT=etapa
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > $DRWVALUE

PORT=uao
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > $DRWVALUE

PORT=uae
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > $DRWVALUE

PORT=ueo
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > $DRWVALUE

PORT=uee
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > $DRWVALUE

PORT=alq
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p2 -n$PORT > $DRWVALUE