#!/bin/sh
#

# parametros
# archivos
SIM=agro
#MA=$SIM.ma
#MA=agro_reduced.ma
MA=agro_fixed.ma
EV=./153/$SIM.ev
LOG=./logs/$SIM.log
OUT=./logs/$SIM.out
#LOG_FULL=$LOG.full
# componente a graficar (CELLDEVS)
COM=campo
#PARSEINFO=true
#HELP=true

#DRW=$SIM.drw
#$(MAKE) -C $(DRWN)

# ejecutables
#SIMU_DIR=/home/daniela/sed/cd++
#SIMU_DIR=/home/d/SED/Tesis/ModelosCellDevs/bin
#SIMU_DIR=/home/d/SED/Tesis/cdpp/cd++
SIMU_DIR=/home/d/SED/SimuSanti/CDPP_ExtendedStates-codename-Santi/src/bin
#SIMU_DIR=$HOME/sed/cd++
SIMU=$SIMU_DIR/cd++
DRAWLOG=$SIMU_DIR/drawlog

#LOGBUFFER=$SIMU_DIR/logbuffer

DRWN=drw
DRWDIR=./${DRWN}
#echo $SIM
#echo $DRWN
#echo $DRWDIR
#echo $(man mkdir)
echo $DRWN
$(mkdir $DRWN )  

# tiempos
TIME=00:00:20:000
STEP=00:00:00:001

#DEBUG="-p$SIM.parser -v$SIM.eval -r"

rm -f $LOG* ${DRWDIR}/*.drw $OUT

SIMU_ARGS="-m$MA"
[ -n "$TIME" ]  &&  SIMU_ARGS="$SIMU_ARGS -t$TIME"
[ -n "$EV" ]    &&  SIMU_ARGS="$SIMU_ARGS -e$EV"
[ -n "$LOG" ]   &&  SIMU_ARGS="$SIMU_ARGS -l$LOG"
[ -n "$OUT" ]   &&  SIMU_ARGS="$SIMU_ARGS -o$OUT"
[ -n "$DEBUG" ] &&  SIMU_ARGS="$SIMU_ARGS $DEBUG"
[ -n "$PARSEINFO" ] &&  SIMU_ARGS="$SIMU_ARGS -pparseinfo.info"
[ -n "$HELP" ] &&  SIMU_ARGS="$SIMU_ARGS -h"
echo "SIMU_ARGS"
echo $SIMU_ARGS
if [ -z "$DEBUGGER" ]; then
    time $SIMU $SIMU_ARGS
else
    $DEBUGGER $SIMU --pargs $SIMU_ARGS
fi

# drawlog
# tiempos
STEP=00:00:00:100

# grafica puertos

#echo Drawlog help
#$DRAWLOG -h

PORT=amb
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=pro
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=eme
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=mgm
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=lu1
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w4 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=lu2
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w4 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=lu3
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w4 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=ue_cota
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=ua_cota
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=ua_tipo
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=deg
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w10 -p2 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=etapa
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w2 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=uao
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=uae
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=ueo
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=uee
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}

PORT=alq
DRWVALUE=${SIM}_${PORT}.drw
echo Running drawlog port $PORT
$DRAWLOG -m$MA -c$COM -l$LOG -i$STEP -w5 -p0 -n$PORT > ${DRWDIR}/${DRWVALUE}